//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirLineReservationSystemProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Airports
    {
        public string IATA_code { get; set; }
        public string ICAO_code { get; set; }
        public string airport_name { get; set; }
        public string city_name { get; set; }
    }
}
