//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirLineReservationSystemProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FlightDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_FlightDetails()
        {
            this.tblTrips = new HashSet<tblTrip>();
        }
    
        public int Id { get; set; }
        public string Prefix { get; set; }
        public string FlightId { get; set; }
        public string TravelDays { get; set; }
        public string DeparturePoint { get; set; }
        public string ArrivalPoint { get; set; }
        public string CabinType { get; set; }
        public string EconomyClassFair { get; set; }
        public string BusinessClassFair { get; set; }
        public string FirstClassFair { get; set; }
        public string FlightStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTrip> tblTrips { get; set; }
    }
}
