//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirLineReservationSystemProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblpassenger_table
    {
        public int ID { get; set; }
        public string Prefix { get; set; }
        public string PassengerID { get; set; }
        public string TicketID { get; set; }
        public string PName { get; set; }
        public string Gender { get; set; }
        public string SeatID { get; set; }
        public Nullable<int> Age { get; set; }
    
        public virtual tblTicket_table tblTicket_table { get; set; }
    }
}
