//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirLineReservationSystemProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSeat
    {
        public string SeatID { get; set; }
        public string Airplane_No { get; set; }
        public string SeatType { get; set; }
    
        public virtual tbl_AircraftDetails tbl_AircraftDetails { get; set; }
    }
}
