//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirLineReservationSystemProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTrip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTrip()
        {
            this.tblTicket_table = new HashSet<tblTicket_table>();
        }
    
        public int ID { get; set; }
        public string prefix { get; set; }
        public string TripID { get; set; }
        public string FlightID { get; set; }
        public string Airplane_No { get; set; }
        public System.DateTime TripDate { get; set; }
        public System.TimeSpan Departure_Time { get; set; }
        public System.TimeSpan Arrival_Time { get; set; }
    
        public virtual tbl_AircraftDetails tbl_AircraftDetails { get; set; }
        public virtual tbl_FlightDetails tbl_FlightDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTicket_table> tblTicket_table { get; set; }
    }
}
