//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirLineReservationSystemProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTicket_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTicket_table()
        {
            this.tblpassenger_table = new HashSet<tblpassenger_table>();
        }
    
        public int Id { get; set; }
        public string Prefix { get; set; }
        public string TicketID { get; set; }
        public string BID { get; set; }
        public string TripID { get; set; }
        public string Phone_No { get; set; }
    
        public virtual tblBooking tblBooking { get; set; }
        public virtual tblBooking tblBooking1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblpassenger_table> tblpassenger_table { get; set; }
        public virtual tblTrip tblTrip { get; set; }
    }
}
